#!/bin/bash

# Detect USB keyboard
bash scripts/detect_keyboards.bash

# Close any active JACK servers and start a new one
bash scripts/start_jackd.bash

# Start the DrumPi program
echo "Starting DrumPi..."
./bin/DrumPi

# When DrumPi has been quit, say goodbye
echo ""
echo ""
echo "DrumPi closed."

# Close JACK server
bash scripts/close_jackd.bash
