#!/bin/bash

# Detect USB keyboard
bash scripts/detect_keyboards.bash

# Trap interupt signals to terminate jackd
trap "killall -s SIGINT jackd; exit" SIGINT

# Close any active JACK servers and start a new one
bash scripts/start_jackd.bash

# If the startup script fails with code 1, no USB audio device is connected
if [ $? -eq 1 ]; then
    echo "Please connect a USB audio device (such as a sound card) and try again."
    trap -- SIGINT
    exit 1
fi

# Release the trapped signal handler
trap -- SIGINT
# Send interrupt signals to the DrumPi
trap "killall -s SIGINT DrumPi" SIGINT

# Start the DrumPi program
echo "Starting DrumPi..."
./bin/DrumPi

# Release the trapped signal handler
trap -- SIGINT

# When DrumPi has been quit, say goodbye
echo ""
echo ""
echo "DrumPi closed."

# Close JACK server
bash scripts/close_jackd.bash
