#ifndef DRUMPI_VERSION_H
#define DRUMPI_VERSION_H

#define PROJECT_NAME "DrumPi"
#define PROJECT_VER  "0.1"
#define PROJECT_VER_MAJOR "0"
#define PROJECT_VER_MINOR "1"
#define PTOJECT_VER_PATCH ""

#endif // DRUMPI_VERSION_H
